[[redirects]]
  from = "grvsh.xyz"
  to = "readme.json"
  status = 301
  force = false
  query = {path = ":path"} # COMMENT: apply this rule for /old-path?path=example
  conditions = {User-Agent = ["curl"]}
